/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_example_jndistudy_example_HelloWorldJNI */

#ifndef _Included_my_example_jndistudy_example_HelloWorldJNI
#define _Included_my_example_jndistudy_example_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_example_jndistudy_example_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_example_jndistudy_example_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     my_example_jndistudy_example_HelloWorldJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_my_example_jndistudy_example_HelloWorldJNI_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     my_example_jndistudy_example_HelloWorldJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_example_jndistudy_example_HelloWorldJNI_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     my_example_jndistudy_example_HelloWorldJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lmy/example/jndistudy/example/UserData;
 */
JNIEXPORT jobject JNICALL Java_my_example_jndistudy_example_HelloWorldJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     my_example_jndistudy_example_HelloWorldJNI
 * Method:    printUserData
 * Signature: (Lmy/example/jndistudy/example/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_example_jndistudy_example_HelloWorldJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
